dataset: "VinDrCXR"
root: "/root/datasets/vindr_cxr/physionet.org/files/vindr-cxr/1.0.0/"
shots: 16
seed: 42

# Training
epochs: 100
lr: 0.0001
wd: 0.0001
batch_size: 32
eval_freq: 25
num_workers: 8
grad_clip: 0.0

# Model / Flow
fm_type: "geodesic"
inv_fm_type: "adapter"
use_op: True
pretrained_op: ""
text_adapter: True
ada_depth: 2
ada_dim: 512
ada_t_dim: 256
alpha: 0. # blending ratio for eval

txt_src: "HF"
txt_model: "Qwen/Qwen3-Embedding-8B"

img_src: "HF"
img_model: "microsoft/rad-dino"